### ISSUE TITLE
create a component to better handle tabular data

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-ui#1]
follow-up of https://github.com/brave/browser-laptop/issues/9032. We need this to unblock https://github.com/brave/browser-laptop/issues/11177 and fix https://github.com/brave/browser-laptop/issues/11551. This component should be prioritized over others.

Component should:

* make use of css grid
* support large amounts of data (such as cookies, browser history, etc)

**Comment by cezaraugusto** [comment]
btw long term this should replace browser-laptop SortableTable component

**Comment by petemill** [comment]
not sure what advantage we get from using css grid for a table, but I'd suggest [React Virtualized](https://bvaughn.github.io/react-virtualized/#/components/Table) for a popular component that can handle thousands of items and render only what's visible. It has a lot of different types of components, helpers and very easily styled. You can use it for lists not just tables, and so put your own completely custom components in.

**Comment by cezaraugusto** [comment]
reason for grid is to make use of `position: sticky` mainly, could be made by other means btw like flexbox or any other positioning of choice just want to avoid table. 

ya React Virtualized is the strongest option by now.

**Comment by petemill** [comment]
by the way, you can use position: sticky on a table, just need to do it on
all the TH cells, not the whole THEAD

**Comment by cezaraugusto** [comment]
after you mentioned I got really into this and found https://bugs.chromium.org/p/chromium/issues/detail?id=702927 so that's possible as you said: https://jsfiddle.net/cezaraugusto/ww6237cL/

which is confusing, iirc it's per spec not supposed to work https://drafts.csswg.org/css-position/#position-property and https://drafts.csswg.org/css-position/#valdef-position-sticky. For me it's still hacky but well we can use table thanks Google 🙂

**Comment by petemill** [comment]
Yeah I know all the hacks :-) well l, not really, just that one because
I’ve been subscribed to all the position sticky bugs waiting for it to
finally happen

**Comment by cezaraugusto** [comment]
we have it now so closing
