### ISSUE TITLE
React should be a 'peerDependency'?

### ISSUE THREAD

**Issue by petemill** [brave/brave-ui#13]
I know that React is labelled a 'devDependency' but shouldn't it be labelled a 'peerDependency' in package.json? Therefore it will use whatever version of react is in the consumer project, we can define a minimum version, and the consumer project will output a warning on 'npm install' if any peerDependency defined by this project isn't met.

**Comment by petemill** [comment]
Actually I see React is defined as a main dependency in the actual brave-ui. That should definitely be a peerDependency. Should help reduce package size?

**Comment by cezaraugusto** [comment]
thanks Pete, not sure but better to. Could you make a PR for that? I can include it in 0.3.0 which is next. 

Not priority but I think Storybook could benefit from that as well, there's a lot of plugins for it.

**Comment by cezaraugusto** [comment]
thanks Pete, not sure but better doing that. Could you make a PR for that? I can include it in 0.3.0 which is next.

Not priority but I think Storybook could benefit from that as well, there's a lot of plugins for it.

**Comment by cezaraugusto** [comment]
ya we're requiring it as a peer dep now see https://github.com/brave/brave-ui/blob/master/package/package.json#L33. Closing
