### ISSUE TITLE
Text in lowercase looks chopped off 

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ui#131]
Brave | 0.55.1 Chromium: 70.0.3528.4 (Official Build) dev (64-bit)
-- | --
Revision | 1911f781145b803e04f2d0b5b1a0146ae69fcbdc-refs/branch-heads/3528@{#9}
OS | Linux

![image](https://user-images.githubusercontent.com/17010094/45167093-71760100-b1c6-11e8-839c-edaa6b822b3d.png)

**Comment by rossmoody** [comment]
This doesn't appear to be the case anymore but regardless should probably house in in Brave Browser if it resurfaces. 
![image](https://user-images.githubusercontent.com/29072694/52237888-8ba03200-287f-11e9-8ebd-07ee4fe04438.png)
