### ISSUE TITLE
Provide a click to copy address option

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ui#135]
![image](https://user-images.githubusercontent.com/17010094/45259449-73dd8400-b39b-11e8-910a-7c94dce7eeaf.png)

![image](https://user-images.githubusercontent.com/17010094/45259454-85bf2700-b39b-11e8-9208-ac245d6d6778.png)

**Comment by NejcZdovc** [comment]
this is just a temporary solution until we add uphold, so we just added as simple as possible
