### ISSUE TITLE
Omnibox region is not distinctly visible in light theme

### ISSUE THREAD

**Issue by n-badri** [brave/brave-ui#136]
Omnibox when not selected can't be easily differentiated from the rest of the address bar region in light mode as opposed to dark mode/incognito mode.  
Please find the snapshots of light and incognito mode for comparison  
 
![capture](https://user-images.githubusercontent.com/19945637/45260242-4a564400-b3ff-11e8-8abf-de7d867ed1b6.PNG)  

![capture2](https://user-images.githubusercontent.com/19945637/45260245-517d5200-b3ff-11e8-84c6-a69d8ed67001.PNG)

**Comment by petemill** [comment]
This is not the correct place to log issues for the brave-browser. I understand the confusing naming @n-badri but this repo is purely for content, not for the browser chrome.

If you have feedback on the preview versions of Brave, I encourage you to visit the community at https://community.brave.com/c/developer-builds

Thanks
