### ISSUE TITLE
add dialog component

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-ui#16]

**Comment by ras9841** [comment]
Hey! Has someone picked this up? I'm an engineering looking to get involved with the Brave project.

**Comment by cezaraugusto** [comment]
hey @ras9841 that's great, thanks for your interest!

cc @NejcZdovc as he's adding some new components and can confirm if dialog is included as well

**Comment by NejcZdovc** [comment]
@cezaraugusto @ras9841 I am in process of already adding it

**Comment by ras9841** [comment]
Thanks for the update! @NejcZdovc, are there other components I could help build?

**Comment by cezaraugusto** [comment]
Hi @ras9841 sorry for the long delay to answer.

Unfortunately, there's no component to work on right now as we are waiting on the brand design to implement them and the others are already in progress.

I'll follow up with you once we have something to work on if you're still interested. Thanks!

**Comment by cezaraugusto** [comment]
this is done already so closing. thanks!
