### ISSUE TITLE
enable branch protection

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ui#18]
this repo should have Branch Protection enabled on master and all prod branches: https://github.com/brave/brave-ui/settings/branches

recommended settings:
![screen shot 2018-02-22 at 1 43 01 pm](https://user-images.githubusercontent.com/549654/36565771-584d2f8a-17d6-11e8-8295-6fc635f9a04b.png)

**Comment by cezaraugusto** [comment]
thanks, addressed.
