### ISSUE TITLE
Button click handlers are running twice

### ISSUE THREAD

**Issue by petemill** [brave/brave-ui#197]

**Comment by kjozwiak** [comment]
@petemill @NejcZdovc can you please add the appropriate labels and a milestone when you have the time? Was this fixed for `0.55.x`?

**Comment by NejcZdovc** [comment]
yes this is for 0.55.x. We don't have labels and milestones in brave-ui

**Comment by kjozwiak** [comment]
@NejcZdovc didn't notice until now that his was in the `brave-ui` repo! Apologies.
