### ISSUE TITLE
Feature request - Extra large toggle

### ISSUE THREAD

**Issue by dlipeles** [brave/brave-ui#277]
Small priority request, could toggle be extended with an extra large mode to match @jenn-rhim's design spec seen here? 

Spec

![screen shot 2018-11-15 at 1 12 40 pm](https://user-images.githubusercontent.com/4713771/48572837-94184a80-e8d8-11e8-919f-3c226c01a756.png)

Current

![screen shot 2018-11-15 at 1 13 00 pm](https://user-images.githubusercontent.com/4713771/48572856-a09ca300-e8d8-11e8-8285-e8c3949caab9.png)

**Comment by rossmoody** [comment]
@dlipeles There are upcoming refinements to the toggle component in general but you should use the large toggle for these for now. We aren't slated to create an extra large atm and if we do we should extend complementary components in the same way.
