### ISSUE TITLE
Separate tabs

### ISSUE THREAD

**Issue by blablalb** [brave/brave-ui#386]
For me this would make multitasking faster and save some space, can we get this feature as an option?
https://i.imgur.com/LvUngWi.png
Check this picture^^^

More ideas [here](https://www.reddit.com/r/brave_browser/comments/at2w6z/brave_is_actually_really_good/)

**Comment by NejcZdovc** [comment]
thank you for your suggestion. Can you please log it into https://github.com/brave/brave-browser.
