### ISSUE TITLE
Keep component folder hierarchy flat

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-ui#397]
Keeping component directory flat and the names singular. I think in the long run it might be a more understandable structure for importing/navigating to have the components be in a flat level instead of within nested folders within the components directory. Might be subjective but I find myself drilling down into and out of folders a lot. 

### Few Examples
 
`components/buttonsIndicators/button` → `components/button`
`dataTables/table` → `table`
`popupModals/alertBox` → `alertBox`
`popupModals/modal` → `modal`

**Comment by petemill** [comment]
We can make this backwards compatible by moving the files and keeping the old files which simply re-export from the new path.
