### ISSUE TITLE
Update and automate license attribution

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-ui#398]
We have to keep the license at the top of each file. We can use the one we are currently using or the one being used in Core. Since the one we are using is 3 lines and the one in core is 4, I think we should stick to what we have. My proposal is to move it to use 
## // 
![image](https://user-images.githubusercontent.com/29072694/53664582-b632a000-3c1d-11e9-841e-c6d34579af46.png)

instead of 
## /* */  

![image](https://user-images.githubusercontent.com/29072694/53664604-c8acd980-3c1d-11e9-8c39-e2cab829703f.png)

for the ridiculous reason that I find it nicer to look at with the left justified slashes.

Additionaly, I wonder if there is some type of automated process to ensure this license is added with a single space underneath via a pre-determined selection of folders? i.e. everything in `src` get this attribution snippet added in some way via automation.

**Comment by petemill** [comment]
You can use a commit hook. But in the scheme of things, this probably isn't worth changing every file. Just enforce as we introduce new files.

Also, the worst offender in this IMO is the uppercase 'Y' mid-sentence 😠
