### ISSUE TITLE
Make sure all components are exported from root

### ISSUE THREAD

**Issue by rossmoody** [brave/brave-ui#414]
Should consider establishing a root directory export file and maybe consistent named/default convention of some sort to alleviate path discrepancies. So instead of imports coming from multiple directories for components we can just do 

`import { Button, WalletIcon } from 'brave-ui'` instead of 

```
import Button from 'brave-ui' 
import {WalletIcon} from 'brave-ui/components/icons
```

**Comment by petemill** [comment]
We already re-export in the root index.ts. Looks like just icons is missing. Usually the reason for not doing this is that webpack would put the entirety of brave-ui in the output JS file if a page just needed to use 1 icon or button. But with [tree shaking](https://webpack.js.org/guides/tree-shaking/), that is mostly alleviated.

By the way, `import Button from 'brave-ui' ` doesn't work and never would, right now it's already `import { Button } from 'brave-ui'` or `import Button from 'brave-ui/components/button'`

**Comment by rossmoody** [comment]
nothing to fix here. thanks for clarifying. :+1:
