### ISSUE TITLE
Tone down the colour of default button

### ISSUE THREAD

**Issue by srirambv** [brave/brave-ui#420]
Default button looks too dark and too black. Default button should have a pleasing soothing colour. 
![image](https://user-images.githubusercontent.com/17010094/54039610-60b44100-4191-11e9-94eb-1c86e60bde8e.png)

**Comment by rossmoody** [comment]
These are Polymer buttons handled on the Core side and this styling should be resolved via: https://github.com/brave/brave-core/pull/2778
