### ISSUE TITLE
Wrong Name on Photo

### ISSUE THREAD

**Issue by jonathansampson** [brave/brave-ui#423]
`Image11` is not Will's.

https://github.com/brave/brave-ui/blob/5bafe81d7043cc87021e9f2aea99867165534d42/stories/features/newTab/default/data/background.ts#L68-L77

**Comment by ryanml** [comment]
@jonathansampson do you have information as to the real photographer's name?

**Comment by rossmoody** [comment]
![image](https://user-images.githubusercontent.com/29072694/56410630-9b020b00-6232-11e9-8002-92c4b1375728.png)

gtg
