### ISSUE TITLE
WalletSummary component clips text on mobile rewards

### ISSUE THREAD

**Issue by antonholmberg** [brave/brave-ui#428]
It looks line the rows in the WalletSummary component clips off a bit of the text when shown in the mobile modal. Maybe we can add a breakpoint and move the amount and the currency to its own line on smaller screeens?

![Screenshot_20190314-222909_Brave](https://user-images.githubusercontent.com/36029900/54396886-d26e1c80-46b4-11e9-895c-66824f2b942a.jpg)

**Comment by NejcZdovc** [comment]
thank you for reporting the issue. This panel is done with native code, so will move issue to the correct repo and close this one

**Comment by antonholmberg** [comment]
@NejcZdovc are you sure? Isn't the content in the panel done with the brave-ui components? I might be wrong but it seemed like they were when I looked at the code in the android-tabs repo.

**Comment by NejcZdovc** [comment]
@antonholmberg some part are done, like rewards page. Panel is done with native code

**Comment by antonholmberg** [comment]
@NejcZdovc Cool! Thanks for the clarification 😄
