### ISSUE TITLE
Rewards: Support Twitter tips

### ISSUE THREAD

**Issue by emerick** [brave/brave-ui#460]
Add support for Twitter tips. This involves the following changes (possibly more to come):

- Add "Tweet Now" button to donation overlay, for tweeting donation to followers.
- Modify `SiteBanner` to support tipping Twitter users
  - Show user's real name and Twitter handle in banner header
  - Show tip message in lower portion of banner
  - Show tipped tweet in a styled box (if Tweet is just a link, skip this step and center tip message)

**Comment by petemill** [comment]
This is handled by the brave-browser issue
