### ISSUE TITLE
Tipping banner should sanitize social media links

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ui#466]
Hackerone issue: https://hackerone.com/reports/577426
Discussion thread in Slack: https://bravesoftware.slack.com/archives/G2KN13Z8C/p1557962234053000
Publishers issue: https://github.com/brave-intl/publishers/issues/1891

**Comment by petemill** [comment]
This should probably be in brave-browser repo @diracdeltas

**Comment by diracdeltas** [comment]
@petemill the fix would actually be in this repo, AFAICT. but happy to open it wherever.

**Comment by diracdeltas** [comment]
superseded by https://github.com/brave/brave-browser/issues/4538
