### ISSUE TITLE
all components should use csstype

### ISSUE THREAD

**Issue by cezaraugusto** [brave/brave-ui#49]
see new rewards components for usage. all components should rely on it

**Comment by cezaraugusto** [comment]
cc @NejcZdovc do you know if we can use this inside styled-components? otherwise since we'll stop using theme props we can close this one

**Comment by NejcZdovc** [comment]
This is not needed in styled-components, because we have linter for css for styled components

**Comment by cezaraugusto** [comment]
ok then closing this
