### ISSUE TITLE
1px colored outline drawn on top of the title bar using windows 10 1809+ 

### ISSUE THREAD

**Issue by ghost** [brave/brave-ui#507]
**ISSUE**
On windows 10 1809 or newer, with the accent color turned off on the title bar and borders, Brave draws a 1px outline on top of the title bar with your system accent color if the browser window is not maximized.

Here's an example (you might have to zoom in a little).
![Bravebug](https://user-images.githubusercontent.com/52277224/60252269-3ca87700-98ca-11e9-8fa0-6629fbd59e93.png)

**HOW TO **REPRODUCE****
Just turn off the accent color on title bars and borders on windows 10 1809 or 1903 and open Brave in windowed mode (unmaximized).

**EXPECTED BEHAVIOR**
The top 1px outline should be dark as the rest of the window borders.

**Comment by rossmoody** [comment]
Thanks for the notice. If you could file this one in: https://github.com/brave/brave-browser/issues

This Repo is used mainly for component driven initiatives.
