### ISSUE TITLE
Rewards : User Wallets - Verified wallet visual indicator is causing confusion versus verified publishers

### ISSUE THREAD

**Issue by alexwykoff** [brave/brave-ui#523]
As noted internally, there is a visual conflict between the verified indicator for a user wallet versus the verified indicator for a publisher in the BAT panel.

<img width="396" alt="Screen Shot 2019-08-05 at 9 04 11 AM" src="https://user-images.githubusercontent.com/1434040/62479231-9b3afd80-b772-11e9-931a-24e61bd4f4c7.png">

**Comment by petemill** [comment]
Please use brave-browser issue for this at https://github.com/brave/brave-browser/issues/5543
