### ISSUE TITLE
npm audit shows 32 vulnerabilites

### ISSUE THREAD

**Issue by diracdeltas** [brave/brave-ui#566]
`found 32 vulnerabilities (11 low, 21 high) in 2303 scanned packages ` < most of these can be fixed automatically with npm audit fix

**Comment by zenparsing** [comment]
@diracdeltas The linked PR ignores https://npmjs.com/advisories/1556. Is that still OK? It looks like fixing 1556 will require a bump of `styled-components` of 2 major versions. It will take a bit more work to make sure that this will not break `brave-ui` users (or fix any breakages).

**Comment by diracdeltas** [comment]
@zenparsing that's fine. i actually excluded 1556 from brave-core for the same reasons: https://github.com/brave/brave-core/blob/master/script/audit_deps.py#L26
